### ISSUE TITLE
include moment-with-locales.js

### ISSUE THREAD

**Issue by jmartsch** [BernhardBaumrock/FieldtypeRockGrid#1]
Hi, it would be nice if you could integrate [moment-with-locales.js](https://momentjs.com/downloads/moment-with-locales.js) instead of only moment.js. So we can have localized dates, for example German.

To use it you have to modify your coldef `datetime.js`:
```document.addEventListener('RockGridReady', function(e) {
  RockGrid.colDefs.datetime = function(col) {
    if(!col) return;

    // set coldefs
    col.valueGetter = function(params) {
      if(typeof params.data == 'undefined') return;
      var val = params.data[col.field];
        var date = moment(val).format('L')
        return date
    }
  
    return RockGrid.colDefs.fixedWidth(col, 150);
  }
});
```
EDIT: you need to set the locale first, for the above code to work:

```
document.addEventListener('RockGridItemBeforeInit', function (e) {
    moment.locale('de');
}
```

**Comment by BernhardBaumrock** [comment]
Thx, I'll have a look when I'm not so busy. This can take several weeks. Or you submit a PR, that might be faster.

**Comment by BernhardBaumrock** [comment]
Thx. I just needed this today and pushed an update to support locales :)
